### ISSUE TITLE
Add Signup activity

### ISSUE THREAD

**Issue by Rahulvs10** [Rahulvs10/Wander#3]
Add a new Activity for the sign-up screen. Follow MVP architecture. 
Refer to Login Activity for example

**Comment by Manish-M2018** [comment]
Hi, what are the details that should be asked from the user in the signup activity?

**Comment by Rahulvs10** [comment]
For now just add first name, last name, email, phone number, country, password and a checkbox for terms and conditions. Make sure that the list is easy to scale in the future.

**Comment by Manish-M2018** [comment]
I will be completing the signup activity by today

**Comment by Manish-M2018** [comment]
I have uploaded the code for signup activity using MVP architecture
